# This is the final, corrected pubspec.yaml combining the best research.
name: fairware_lift
description: "A privacy-first workout tracker with offline-first data and world-class exports."
publish_to: 'none'
version: 1.0.0+1

# Corrected SDK environment from LLM #2 to support new package versions.
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.32.0"

# Comprehensive dependency list from LLM #1's research.
dependencies:
  flutter:
    sdk: flutter

  # Firebase - Unchanged
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0
  firebase_crashlytics: ^4.1.0

  # State Management & DB - Unchanged
  flutter_riverpod: ^2.6.0
  drift: ^2.28.0
  sqlite3_flutter_libs: ^0.5.40
  path: ^1.8.2

  # --- V2 EMBEDDING COMPATIBILITY UPGRADES ---
  path_provider: ^2.1.5         # For modern Flutter/AGP compatibility.
  flutter_local_notifications: ^17.2.1 # Already v2 compatible.
  workmanager: ^0.9.0+3          # CRITICAL FIX: Removes V1 APIs and fixes Registrar/shim errors.
  vibration: ^3.1.3              # CRITICAL FIX: Uses modern Android Embedding v2.
  audioplayers: ^6.5.1           # Upgrade to current stable v2 version.
  image_picker: ^1.1.2           # Proactive fix for known v1 embedding build errors.
  file_picker: ^8.3.5            # Upgrade to current stable to avoid build issues.
  open_filex: ^4.7.0             # Upgrade to latest with modern Gradle compatibility.
  
  # Pure Dart / Already Compatible - Unchanged
  pdf: ^3.10.4
  printing: ^5.11.0
  csv: ^6.0.0
  fl_chart: ^0.68.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.1.0

  # Code Gen - Unchanged
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  drift_dev: ^2.28.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true